import { useEffect, useState } from 'react'
import { Link, useSearchParams, useNavigate } from 'react-router-dom'
import { createReport, getLeaderMissions } from '../lib/phase5'

const initial = { missionId: '', summary: '', activitiesDone: '', results: '', difficulties: '', recommendations: '', participantsCount: 0, performedOn: '', observations: '' }
export default function LeaderReportNew() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const [values, setValues] = useState({ ...initial, missionId: params.get('mission') || '' }); const [missions, setMissions] = useState([]); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { getLeaderMissions().then((data) => setMissions(data.filter((mission) => mission.status === 'completed'))).catch(() => setMessage('Les missions réalisées sont indisponibles.')) }, [])
  function update(event) { setValues((current) => ({ ...current, [event.target.name]: event.target.value })) }
  async function submit(event) { event.preventDefault(); setSaving(true); try { await createReport(values); navigate('/leader/rapports') } catch (error) { setMessage(error.message || 'Le rapport n’a pas pu être envoyé.') } finally { setSaving(false) } }
  return <main className="page-section dashboard-page"><div className="container"><div className="dashboard-heading"><div><span className="eyebrow">Espace leader</span><h1>Nouveau rapport</h1></div><Link to="/leader/rapports" className="button button-outline">Mes rapports</Link></div>{message && <div className="form-notice notice-error">{message}</div>}<form className="admin-panel phase5-form report-form" onSubmit={submit}><label>Mission<select required name="missionId" value={values.missionId} onChange={update}><option value="">Sélectionner une mission réalisée</option>{missions.map((mission) => <option key={mission.id} value={mission.id}>{mission.title}</option>)}</select></label><label>Résumé<textarea required name="summary" value={values.summary} onChange={update} /></label><label>Activités réalisées<textarea required name="activitiesDone" value={values.activitiesDone} onChange={update} /></label><label>Résultats obtenus<textarea required name="results" value={values.results} onChange={update} /></label><div className="form-grid-two"><label>Date de réalisation<input required type="date" name="performedOn" value={values.performedOn} onChange={update} /></label><label>Participants<input required min="0" type="number" name="participantsCount" value={values.participantsCount} onChange={update} /></label></div><label>Difficultés rencontrées<textarea name="difficulties" value={values.difficulties} onChange={update} /></label><label>Recommandations<textarea name="recommendations" value={values.recommendations} onChange={update} /></label><label>Observations<textarea name="observations" value={values.observations} onChange={update} /></label><button className="button button-primary" disabled={saving} type="submit">{saving ? 'Envoi…' : 'Envoyer le rapport'}</button></form></div></main>
}
